name: Build and Push Multi-Arch Image

on:
  workflow_dispatch:

env:
  IMAGE_NAME: hath               # Image naming, 需小寫
  DOCKERHUB_OWNER: tdcpf         # Docker Hub user 或 org, 需小寫
  GHCR_OWNER: tdcpf              # GHCR user 或 org, 需小寫

jobs:
  build-multiarch-natively:
    strategy:
      matrix:
        arch: [arm64, amd64]
    runs-on: ${{ matrix.arch == 'amd64' && 'ubuntu-latest' || 'ubuntu-24.04-arm'}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platform: linux/${{ matrix.arch }}
          push: true
          tags: ghcr.io/${{ env.GHCR_OWNER }}/${{ env.IMAGE_NAME }}:latest-${{ matrix.arch }}

  create-manifest:
    needs: build-multiarch-natively
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Create multi-arch manifest
        run: |
          docker manifest create ghcr.io/${{ github.repository }}:latest \
            ghcr.io/${{ env.GHCR_OWNER }}/${{ env.IMAGE_NAME }}:latest-arm64 \
            ghcr.io/${{ env.GHCR_OWNER }}/${{ env.IMAGE_NAME }}:latest-amd64
          docker manifest push ghcr.io/${{ env.GHCR_OWNER }}/${{ env.IMAGE_NAME }}:latest
