name: Build and Push Multi-Arch Image

on:
  workflow_dispatch:

env:
  IMAGE_NAME: hath               # Image naming, 需小寫
  DOCKERHUB_OWNER: tdcpf         # Docker Hub user 或 org, 需小寫
  GHCR_OWNER: tdcpf              # GHCR user 或 org, 需小寫

jobs:
  build-multiarch-natively:
    strategy:
      matrix:
        arch: [arm64, amd64]
    runs-on: ${{ matrix.arch == 'amd64' && 'ubuntu-latest' || 'ubuntu-24.04-arm'}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

#      - name: Composite Docker metadata
#        id: meta
#        uses: docker/metadata-action@v5
#        with:
#          images: |
#            docker.io/${{ env.DOCKERHUB_OWNER }}/${{ env.IMAGE_NAME }}
#            ghcr.io/${{ env.GHCR_OWNER }}/${{ env.IMAGE_NAME }}
#          tags: |
#            type=sha
#            type=ref,event=tag
#            type=semver,pattern={{version}}
#          flavor: |
#            suffix=-${{ matrix.arch }}
#            suffixLatest=true
#            latest=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/${{ matrix.arch }}
          push: true
          provenance: false
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            docker.io/${{ env.DOCKERHUB_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ matrix.arch }}
            ghcr.io/${{ env.GHCR_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ matrix.arch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  create-manifest:
    needs: build-multiarch-natively
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Create multi-arch manifest (docker manifest way)
        run: |
          docker manifest create docker.io/${{ env.DOCKERHUB_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            docker.io/${{ env.DOCKERHUB_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-arm64 \
            docker.io/${{ env.DOCKERHUB_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-amd64
          docker manifest create ghcr.io/${{ env.GHCR_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            ghcr.io/${{ env.GHCR_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-arm64 \
            ghcr.io/${{ env.GHCR_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-amd64
          docker manifest push \
            docker.io/${{ env.DOCKERHUB_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            ghcr.io/${{ env.GHCR_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      #- name: Create multi-arch manifest (buildx way)
